Make use of pingInterval while holding an active websocket connection
Behaviour before this commit:

```
2019-04-16T17:00:04.995Z-TID:1/V/DefaultNetworkModeService: updateNetworkMode: OFFLINE
2019-04-16T17:00:05Z-TID:1/W/AVS: NOT IMPLEMENTED: networkChanged

2019-04-16T17:00:12.012Z-TID:1/V/DefaultNetworkModeService: updateNetworkMode: _4G
2019-04-16T17:00:12.015Z-TID:1/W/AVS: NOT IMPLEMENTED: networkChanged
```

At this point, the websocket connection is effectively broken (no new messages arrive), but OkHttpWebSocketFactory and WSPushService did not notice this. There is no log entry showing that a `SocketEvent.Closed` has been sent.

After this commit/PR:

After a change to network mode:

```
2019-04-16T17:43:45.536Z-TID:1/V/DefaultNetworkModeService: updateNetworkMode: OFFLINE
2019-04-16T17:43:45.540Z-TID:1/W/AVS: NOT IMPLEMENTED: networkChanged

2019-04-16T17:43:53.734Z-TID:1/V/DefaultNetworkModeService: updateNetworkMode: _4G
2019-04-16T17:43:53.740Z-TID:1/W/AVS: NOT IMPLEMENTED: networkChanged

(...)
```

up to 30 seconds later we can see a "didn't receive pong", which then fails the websocket connection:

```
2019-04-16T17:44:16.164Z-TID:1641/W/OkHttpWebSocketFactory$: WebSocket connection has been failed.
java.net.SocketTimeoutException: sent ping but didn't receive pong within 30000ms (after 1 successful ping/pongs)
	at okhttp3.internal.ws.RealWebSocket.writePingFrame(RealWebSocket.java:546)
	at okhttp3.internal.ws.RealWebSocket$PingRunnable.run(RealWebSocket.java:530)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:278)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:273)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
(...)
```

which then enters the normal routine to restart the websocket connection.

Note that the choice of 30 seconds as pingInterval is arbitrary, and
could be changed.

Fixes #532